---
# This file is managed via modulesync
# https://github.com/voxpupuli/modulesync
# https://github.com/voxpupuli/modulesync_config
HOSTS:
  dns-xenial-master:
    roles:
    - default
    - dnsmaster
    platform: ubuntu-16.04-amd64
    hypervisor: docker
    image: ubuntu:16.04
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'apt-get install -y net-tools wget locales'
      - 'locale-gen en_US.UTF-8'
  dns-xenial-signer:
    roles:
    - dnssigner
    platform: ubuntu-16.04-amd64
    hypervisor: docker
    image: ubuntu:16.04
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'apt-get install -y net-tools wget locales'
      - 'locale-gen en_US.UTF-8'
  dns-xenial-slave:
    roles:
    - dnsslave
    platform: ubuntu-16.04-amd64
    hypervisor: docker
    image: ubuntu:16.04
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'apt-get install -y net-tools wget locales'
      - 'locale-gen en_US.UTF-8'
CONFIG:
  trace_limit: 200
  masterless: true
...
# vim: syntax=yaml
