---
# This file is managed via modulesync
# https://github.com/voxpupuli/modulesync
# https://github.com/voxpupuli/modulesync_config
HOSTS:
  dns-trusty-master:
    roles:
    - default
    - dnsmaster
    platform: ubuntu-14.04-amd64
    hypervisor: docker
    image: ubuntu:14.04
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'rm /usr/sbin/policy-rc.d'
      - 'rm /sbin/initctl; dpkg-divert --rename --remove /sbin/initctl'
      - 'apt-get install -y net-tools wget'
      - 'locale-gen en_US.UTF-8'
    ip: 10.255.255.2
  dns-trusty-signer:
    roles:
    - dnssigner
    platform: ubuntu-14.04-amd64
    hypervisor: docker
    image: ubuntu:14.04
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'rm /usr/sbin/policy-rc.d'
      - 'rm /sbin/initctl; dpkg-divert --rename --remove /sbin/initctl'
      - 'apt-get install -y net-tools wget'
      - 'locale-gen en_US.UTF-8'
    ip: 10.255.255.3
  dns-trusty-slave:
    roles:
    - dnsslave
    platform: ubuntu-14.04-amd64
    hypervisor: docker
    image: ubuntu:14.04
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'rm /usr/sbin/policy-rc.d'
      - 'rm /sbin/initctl; dpkg-divert --rename --remove /sbin/initctl'
      - 'apt-get install -y net-tools wget'
      - 'locale-gen en_US.UTF-8'
    ip: 10.255.255.4
CONFIG:
  trace_limit: 200
  masterless: true
...
# vim: syntax=yaml
