fixtures:
    symlinks:
      dns: "#{source_dir}"
    repositories:
      stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
        ref: 4.14.0
      concat:
        repo: https://github.com/puppetlabs/puppetlabs-concat.git
      nsd:
        repo: https://github.com/icann-dns/puppet-nsd.git
      knot:
        repo: https://github.com/icann-dns/puppet-knot.git
      tea:
        repo: https://github.com/icann-dns/puppet-tea.git
      python:
        repo: https://github.com/stankevich/puppet-python.git
