fixtures:
    symlinks:
      dns: "#{source_dir}"
    repositories:
      stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
        ref: 4.12.0
      concat:
        repo: https://github.com/puppetlabs/puppetlabs-concat.git
      nsd:
        repo: https://github.com/icann-dns/puppet-nsd.git
        ref: 0.1.8
      knot:
        repo: https://github.com/icann-dns/puppet-knot.git
        ref: 0.1.3
      tea:
        repo: https://github.com/icann-dns/puppet-tea.git
        ref: v0.2.7
      python:
        repo: https://github.com/stankevich/puppet-python.git
