fixtures:
    symlinks:
      dns: "#{source_dir}"
    forge_modules:
      stdlib: "puppetlabs/stdlib"
      concat: "puppetlabs/concat"
      knot: "icann/knot"
      nsd: "icann/nsd"
      tea: "icann/tea"
      python: "puppet/python"
