fixtures:
    symlinks:
      dns: "#{source_dir}"
    forge_modules:
      stdlib: "puppetlabs/stdlib"
      motd: "icann/motd"
      concat: "puppetlabs/concat"
      tea: "icann/tea"
      python: "puppet/python"
      cron_core:
        repo: "puppetlabs/cron_core"
        ref: "1.0.0"
        puppet_version: ">= 6.0.0"
    repositories:
      augeas: "https://github.com/camptocamp/puppet-augeas.git"
      knot: "https://git.dns.icann.org/root/puppet-knot"
      nsd: "https://git.dns.icann.org/root/puppet-nsd"
