stages:
  - rspec
  - rubocop
  - beaker_apply
  - beaker_agent

before_script:
  - rvm -v
  - ruby -v
  - bundle --version
  - gem --version
  - rvm use 2.3
  - rm Gemfile.lock || true
  - bundle install

rspec:
  stage: rspec
  script:
    - bundle exec rake test

rubocop:
  stage: rubocop
  script:
    - bundle exec rake rubocop

beaker_trusty_apply:
  stage: beaker_apply
  variables:
    BEAKER_set: docker/ubuntu-14.04
    BEAKER_TESTMODE: apply
  script:
    -  bundle exec rake beaker

beaker_xenial_apply:
  stage: beaker_apply
  variables:
    BEAKER_set: docker/ubuntu-16.04
    BEAKER_TESTMODE: apply
  script:
    -  bundle exec rake beaker

beaker_trusty_agent:
  stage: beaker_agent
  variables:
    BEAKER_set: docker/ubuntu-master-14.04
    BEAKER_TESTMODE: agent
  script:
    -  bundle exec rake beaker

beaker_xenial_agent:
  stage: beaker_agent
  variables:
    BEAKER_set: docker/ubuntu-master-16.04
    BEAKER_TESTMODE: agent
    BEAKER_debug: 'on'
  script:
    -  bundle exec rake beaker
