image: ruby:2.4

cache:
  untracked: false

variables:
  BEAKER_PUPPET_COLLECTION: puppet5
  PUPPET_GEM_VERSION: "~> 5.0"

before_script:
  - pwd
  - ruby -v
  - bundle --version
  - gem --version
  - rm Gemfile.lock || true
  - rm -rf ./vendor || true
  - bundle install --path=${BUNDLE_PATH:-vendor/bundle}

stages:
  - syntax
  - rubocop      
  - rspec
  - beaker

lint:
  stage: lint
  script:
    - bundle exec rake validate lint

rubocop:
  stage: lint
  script:
    - bundle exec rake rubocop

rspec:
  stage: rspec
  script:
    - bundle exec rake spec

beaker_xenial_apply:
 stage: beaker
 variables:
   BEAKER_set: docker/ubuntu-multi-18.04
   BEAKER_TESTMODE: apply
 script:
   -  bundle exec rake beaker

beaker_xenial_agent:
 stage: beaker
 variables:
   BEAKER_set: docker/ubuntu-master-18.04
   BEAKER_TESTMODE: agent
 script:
   -  bundle exec rake beaker
