---
os: linux
sudo: false
dist: bionic
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.4.10
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet5 PUPPET_GEM_VERSION="~> 5.0" BEAKER_debug=true
jobs:
  fast_finish: true
  include:
    - stage: spec and lint
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    - stage: spec and lint
      env: CHECK=parallel_spec
    - stage: spec and lint
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
    - stage: acceptance
      bundler_args: 
      dist: xenial
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=docker/ubuntu-16.04 BEAKER_TESTMODE=apply
      script: bundle exec rake beaker
      services: docker
      sudo: required
    - stage: acceptance
      bundler_args: 
      dist: bionic
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=docker/ubuntu-18.04 BEAKER_TESTMODE=apply
      script: bundle exec rake beaker
      services: docker
      sudo: required
   - stage: deploy
      env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
notifications:
  email: false
deploy:
  provider: puppetforge
  user: icann
  password:
    secure: "cL82bKko4SXs+Kheh5pY9BwcnhiXMbZGYgD8RqAItdE0NoKt9EA2Y7HZjSzgR0Y1za9hTx/CjXOUq2oYUC3Kbp0A/jJdFwot9hfpxXeTEVAizYA7CK5rBaXpSvXK+gTpDdc9UNGQT6ahpL4XR4wUn6GNfp7da6tKrXykAFIGv8IdldID8ayoGGqY2oICv5Ot6KSgJIRGVSFbWAE8eO/nqo07O92inTQEdco7eJRZ3sk4DQlTdavhjfgrtl+nxXosF2qK39I75vHrm7wLYtvpx7iTo60C1RqIj/1CGT4GhUkmMiDS2UIebyKnvRBHZYqLcpvl3P4KPrhYdYamtSuU9y4WGPYUjl+rZuUJ+m8GpUseKYhqta64UIuu+d/Ndun1enHEX+eQ8DJTAa3/N6geiwGdmEsyLx3qlfEClwtLadOK3g3IYh0M9Pn9p3/+ePV8JwmGLCUWfRFQhKVwLvrl12NfLSKDD+tPFXQVh+b66y6YNO0sUcVmNOhQJK17/29v61MTJnAQFyXcxfGhcOO6K/N1XLpsuniXO1ZAc5WY+zaqMch6qPniHZxju1wGWVvUsq/A1smQOJjKbM6FA3a43bmWIiNwxwfvIQybJwV/vdotDDznYE0qSVIZVgbhdiPpCqea3b/g2DaoJMHAs/YmIHa/8X4rae95bJVeYGWpKnY="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
