---
sudo: false
dist: trusty
language: ruby
cache: bundler
bundler_args: --without system_tests development
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
env: ["PUPPET_VERSION=\"~> 4.6.0\" STRICT_VARIABLES=yes", "PUPPET_VERSION=\"~> 4.7.0\" STRICT_VARIABLES=yes", "PUPPET_VERSION=\"~> 4.8.0\" STRICT_VARIABLES=yes", "PUPPET_VERSION=\"~> 4.9.0\" STRICT_VARIABLES=yes", "PUPPET_VERSION=\"~> 4.10.0\" STRICT_VARIABLES=yes", "PUPPET_VERSION=\"~> 5.0.0\" STRICT_VARIABLES=yes"]
rvm: ["2.2.0", "2.3.0", "2.4.0"]
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.0
    bundler_args: --without development
    dist: trusty
    env: BEAKER_TESTMODE=apply BEAKER_debug=true BEAKER_set=docker/ubuntu-14.04 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.3.0
    bundler_args: --without development
    dist: trusty
    env: BEAKER_TESTMODE=apply BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.3.0
    bundler_args: --without development
    dist: trusty
    env: BEAKER_TESTMODE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-master-14.04 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.3.0
    bundler_args: --without development
    dist: trusty
    env: BEAKER_TESTMODE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-master-16.04 CHECK=beaker
    services: docker
    sudo: required
notifications:
  email: false
deploy:
  provider: puppetforge
  deploy:
    branch: ha-bug-puppet-forge
  user: icann
  password:
    secure: "cL82bKko4SXs+Kheh5pY9BwcnhiXMbZGYgD8RqAItdE0NoKt9EA2Y7HZjSzgR0Y1za9hTx/CjXOUq2oYUC3Kbp0A/jJdFwot9hfpxXeTEVAizYA7CK5rBaXpSvXK+gTpDdc9UNGQT6ahpL4XR4wUn6GNfp7da6tKrXykAFIGv8IdldID8ayoGGqY2oICv5Ot6KSgJIRGVSFbWAE8eO/nqo07O92inTQEdco7eJRZ3sk4DQlTdavhjfgrtl+nxXosF2qK39I75vHrm7wLYtvpx7iTo60C1RqIj/1CGT4GhUkmMiDS2UIebyKnvRBHZYqLcpvl3P4KPrhYdYamtSuU9y4WGPYUjl+rZuUJ+m8GpUseKYhqta64UIuu+d/Ndun1enHEX+eQ8DJTAa3/N6geiwGdmEsyLx3qlfEClwtLadOK3g3IYh0M9Pn9p3/+ePV8JwmGLCUWfRFQhKVwLvrl12NfLSKDD+tPFXQVh+b66y6YNO0sUcVmNOhQJK17/29v61MTJnAQFyXcxfGhcOO6K/N1XLpsuniXO1ZAc5WY+zaqMch6qPniHZxju1wGWVvUsq/A1smQOJjKbM6FA3a43bmWIiNwxwfvIQybJwV/vdotDDznYE0qSVIZVgbhdiPpCqea3b/g2DaoJMHAs/YmIHa/8X4rae95bJVeYGWpKnY="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
